# -*- coding: utf-8 -*-
"""clean_data.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rObdWgYwzVLbSl_VHMKBXnB4a07-gk3Z
"""

import pandas as pd
import os

def main():
    # Create output folder if missing
    os.makedirs('output', exist_ok=True)

    # Load raw data
    df = pd.read_csv('data/nz_banking_data.csv')

    # Clean: drop duplicates and nulls
    df = df.drop_duplicates()
    df = df.dropna()

    # If needed, convert categorical variables, e.g. Gender
    if 'Gender' in df.columns:
        df['Gender'] = df['Gender'].map({'Male': 0, 'Female': 1})

    # Save cleaned data
    df.to_csv('output/cleaned_nz_banking_data.csv', index=False)
    print("✅ Cleaning complete, cleaned data saved to output/cleaned_nz_banking_data.csv")

if __name__ == "__main__":
    main()